"""Add is_actived field for user

Revision ID: 129e219d7a97
Revises: 54b9ed385bdd
Create Date: 2015-12-30 14:42:19.551566

"""

# revision identifiers, used by Alembic.
revision = '129e219d7a97'
down_revision = '54b9ed385bdd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_actived', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_actived')
    ### end Alembic commands ###
