"""Add user forgot password table

Revision ID: 4809bb0fa09
Revises: 2f9f150dc4c5
Create Date: 2015-07-22 10:58:10.158012

"""

# revision identifiers, used by Alembic.
revision = '4809bb0fa09'
down_revision = '2f9f150dc4c5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_forgot_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=40), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_forgot_passwords')
    ### end Alembic commands ###
